[package]
name = "exabind-core"
version = "0.1.0-dev"
edition = "2021"

[dependencies]
anpa = "0.9.0"
bit-set = "0.8.0"
dirs = "5.0.1"
crossterm = "0.28.1"
clap = { version = "4.5.21", features = ["derive"] }